@startuml
!include https://raw.githubusercontent.com/johthor/DomainStory-PlantUML/main/domainStory.puml

Person(Alice)


Boundary(Booking) {

    Document(room1, criteria room)
    Document(room2, Room)


    System(bookingSystem, Booking System, )

}
  activity(_, Alice, search, room1, on, bookingSystem)
  activity(_, bookingSystem, recomands, room2, for, Alice)


@enduml