@startuml

object hotel
hotel : id
hotel : listRoom

object room

room : roomNumber
room : capacity

hotel *-- room

object price

price : value
price : currency
price : period

hotel *-- price

@enduml